server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/bmw_parts?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0896337619uktc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
nhtsa.api.base-url=https://vpic.nhtsa.dot.gov/api/vehicles/decodevin/
logging.level.com.bmwparts=INFO
